name: Continuous integration and deployment

on:
  push:
    branches:
      - main
    tags:
      - 'milestone/*'
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:

    # Only pushes of tags trigger a release creation
    - name: Create the release
      id: create_release
      if: startsWith('refs/tags/', github.ref)
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: startsWith('refs/tags/milestone', github.ref)
    - name: Attach build distribution to the release
      if: startsWith('refs/tags/', github.ref)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: README.md
        asset_name: README
        asset_content_type: text/plain

